apiVersion: app.qy.com/v1
kind: AppService
metadata:
  name: appservice-sample
  namespace: qyapp
spec:
  size: 2
  image: nginx:1.7.9
  port:
    port: 80
    nodePort: 30002
    targetPort: 80
  envs:
    - name: EnvA
      value: valueA
    - name: EnvB
      value: "13"
  ingress:
    host: samples.appservice.qyapp.com
    path: /api/v2/design